const developmentProjects = [
  {
    id: 1,
    projectTitle: 'Personal Portfolio Page',
    imgURL: './images/Projects/development/TB2-min.jpg',
    description:
      'A responsive personal website for a professional bioanalyst. This project designed and created by me.',
    subTitle: 'Created with',
    subDescription: 'React, Gatsby',
    buttonLabel: 'Live View',
    link1: 'https://www.tiborborsos.com/',
    buttonLabel2: '',
    link2: '',
    buttonLabel3: '',
    link3: '',
  },
  {
    id: 2,
    projectTitle: 'ProShop',
    imgURL: './images/Projects/development/proShop.jpg',
    description:
      'A responsive eCommerce platform with the following functionality:' +
      '- User profile with orders, - Admin profile with user/product management and order details page, - Product search feature, pagination, reviews and ratings, - Checkout process (shipping, payment method, etc), - Full featured shopping cart, -PayPal / credit card integration,  ',
    subTitle: 'Created with',
    subDescription: 'React, Redux, Node, Express & MongoDB',
    buttonLabel: 'Live View',
    link1: 'https://g-proshopapp.herokuapp.com/',
    buttonLabel2: 'View on Github',
    link2: 'https://github.com/Norewal/ProShop',
    buttonLabel3: '',
    link3: '',
  },
  {
    id: 3,
    projectTitle: 'Art Gallery',
    imgURL: './images/Projects/development/judit1.jpg',
    description:
      'Judit Tamas is a hobby artist, who has many beautiful works of art with different techniques. This website shows her and her world.',
    subTitle: 'Created with',
    subDescription: 'HTML, CSS, Javascript',
    buttonLabel: 'Live View',
    link1: 'https://www.judittamas.eu/',
    buttonLabel2: '',
    link2: '',
    buttonLabel3: '',
    link3: '',
  },
  {
    id: 4,
    projectTitle: 'Say Yes - Landing page',
    imgURL: './images/Projects/development/wedding1.jpg',
    description:
      "I am building this landing page to put my knowledge of Front-end into practice. It is still in progress, but will be a complete webshop, when it's done.",
    subTitle: 'Created with',
    subDescription: 'HTML, CSS, Javascript',
    buttonLabel: 'Live View',
    link1: 'https://ecommerce-wedding.netlify.app/',
    buttonLabel2: '',
    link2: '',
    buttonLabel3: '',
    link3: '',
  },
  {
    id: 5,
    projectTitle: 'To-Do List',
    imgURL: './images/Projects/development/todolist21.jpg',
    description:
      'I built this To-Do List web application to put my knowledge of Front-end and Back-end into practice.',
    subTitle: 'Created with',
    subDescription: 'HTML, CSS, Javascript, Node.js, MongoDB',
    buttonLabel: 'Live View',
    link1: 'https://g-todolist.herokuapp.com/',
    buttonLabel2: 'View on Github',
    link2: 'https://github.com/Norewal/todolist-',
    buttonLabel3: '',
    link3: '',
  },
  {
    id: 6,
    projectTitle: 'Newsletter Signup',
    imgURL: './images/Projects/development/newsletter1.jpg',
    description:
      "This app uses MailChimp's API to subscribe users to a newsletter.",
    subTitle: 'Created with',
    subDescription: 'Bootstrap, Node/Express.js',
    buttonLabel: 'Live View',
    link1: 'https://g-newsletter-signup.herokuapp.com/',
    buttonLabel2: 'View on Github',
    link2: 'https://github.com/Norewal/newsletter-signup-node.js',
    buttonLabel3: '',
    link3: '',
  },
];

export default developmentProjects;
